### ISSUE TITLE
doesn't use bootstrap 4

### ISSUE THREAD

**Issue by jnruel** [mrjeffreylarge/Wishlistapp#1]

**Comment by jeffumbricht** [comment]
Curretly in beta 2 and breaking changes to come in beta 3.

> We’ve done our best to prevent breaking changes, but we had to sneak some in. Regrettably, we’ll also have a few more coming in Beta 3, too. 

https://blog.getbootstrap.com/2017/10/19/bootstrap-4-beta-2/

**Comment by jnruel** [comment]
fair enough

**Comment by jeffumbricht** [comment]
Bootstrap 4 finally has stable release. Upgrade coming soon

**Comment by jeffumbricht** [comment]
Resolved with 562c870b4322a5e20e0b1da04a9dbf1b5dfed83a
